//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 25

//_\SV
// Copyright (c) 2020 Sonal Pinto
// SPDX-License-Identifier: Apache-2.0
//
// Converted to TL-Verilog by Claude.

/*
Controller for 1BitSquared 7 Segment Display PMOD

Ref: https://1bitsquared.com/collections/fpga/products/pmod-7-segment-display
Sch: https://github.com/icebreaker-fpga/icebreaker-pmod/blob/master/7segment/v1.1a/7segment-sch.pdf

      A
     ---
  F | G | B
     ---
  E |   | C
     ---
      D

0 : 7'b1000000
1 : 7'b1111001
2 : 7'b0100100
3 : 7'b0110000
4 : 7'b0011001
5 : 7'b0010010
6 : 7'b0000010
7 : 7'b1111000
8 : 7'b0000000
9 : 7'b0010000
A : 7'b0001000
B : 7'b0000011
C : 7'b1000110
D : 7'b0100001
E : 7'b0000110
F : 7'b0001110

*/

module snowflake_7sd_driver (
    input  logic        clk,
    input  logic        rstz,
    input  logic        en,
    input  logic [6:0]  a,
    input  logic [6:0]  b,
    output logic [6:0]  disp,
    output logic        sel
);
// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$aa.
logic [6 : 0] DEFAULT_aa_a0;

// For |default$bb.
logic [6 : 0] DEFAULT_bb_a0;

// For |default$disp.
logic [6 : 0] DEFAULT_disp_n1,
              DEFAULT_disp_a0;

// For |default$en.
logic DEFAULT_en_a0;

// For |default$reset.
logic DEFAULT_reset_a0;

// For |default$rollover.
logic DEFAULT_rollover_n1,
      DEFAULT_rollover_a0;

// For |default$rstz.
logic DEFAULT_rstz_a0;

// For |default$sel.
logic DEFAULT_sel_n1,
      DEFAULT_sel_a0;

// For |default$tick.
logic DEFAULT_tick_a0;

// For |default$timer.
logic [15 : 0] DEFAULT_timer_n1,
               DEFAULT_timer_a0;




   //
   // Scope: |default
   //

      // Staging of $disp.
      always_ff @(posedge clk) DEFAULT_disp_a0[6 : 0] <= DEFAULT_disp_n1[6 : 0];

      // Staging of $rollover.
      always_ff @(posedge clk) DEFAULT_rollover_a0 <= DEFAULT_rollover_n1;

      // Staging of $sel.
      always_ff @(posedge clk) DEFAULT_sel_a0 <= DEFAULT_sel_n1;

      // Staging of $timer.
      always_ff @(posedge clk) DEFAULT_timer_a0[15 : 0] <= DEFAULT_timer_n1[15 : 0];



// ---------- Generated Code Ends ----------
//_\TLV
   // Connect Verilog inputs:
   //_|default
      //_@0
         assign DEFAULT_rstz_a0 = rstz;
         assign DEFAULT_en_a0 = en;
         assign DEFAULT_aa_a0[6 : 0] = a;
         assign DEFAULT_bb_a0[6 : 0] = b;
   //_\source wip.tlv 6   // Instantiated from wip.tlv, 83 as: m5+snowflake_7sd_driver(/top)
      //_|default
         //_@0
            // Internal positively-asserted reset, derived from the negatively-asserted,
            // synchronous reset input rstz.
            assign DEFAULT_reset_a0 = ~ DEFAULT_rstz_a0;
            // timer
            assign DEFAULT_timer_n1[15 : 0] = DEFAULT_timer_a0 + 1'b1;
            assign DEFAULT_rollover_n1 = DEFAULT_timer_a0[15];
   
            // 2.7ms = 2**16 * (1/24MHz)
            assign DEFAULT_tick_a0 = DEFAULT_rollover_a0 & ~ DEFAULT_timer_a0[15];
   
            // display output mux
            assign DEFAULT_sel_n1 = (DEFAULT_reset_a0 || ~ DEFAULT_en_a0) ? 1'b0 :
                       DEFAULT_tick_a0             ? ~ DEFAULT_sel_a0 :
                                            DEFAULT_sel_a0;
            assign DEFAULT_disp_n1[6 : 0] = (DEFAULT_reset_a0 || ~ DEFAULT_en_a0) ? '1 :          // anode, blanks display
                               DEFAULT_tick_a0             ? (DEFAULT_sel_a0 ? DEFAULT_bb_a0 : DEFAULT_aa_a0) :
                                                    DEFAULT_disp_a0;
   //_\end_source
   // Connect Verilog outputs:
   //_|default
      //_@0
         assign sel = DEFAULT_sel_a0;
         assign disp = DEFAULT_disp_a0;
//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
