//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 41

//_\SV
// Copyright (c) 2020 Sonal Pinto
// SPDX-License-Identifier: Apache-2.0
//
// Converted to TL-Verilog by Claude.

/*
Simple Input Debouncer for groups of GPIO
*/

module input_debouncer #(
    parameter N = 16,
    parameter DEBOUNCE = 16
)(
    input  logic        clk,
    input  logic        rstz,
    output logic [N-1:0] read,
    input  logic [N-1:0] gpio_in
);
// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


genvar gpio;


//
// Signals declared top-level.
//

// For |default$gpio_in.
logic [N-1:0] DEFAULT_gpio_in_a0;

// For |default$resetn.
logic DEFAULT_resetn_a0;

// For |default$resetn_meta.
logic DEFAULT_resetn_meta_a0;

// For |default$tick.
logic DEFAULT_tick_a0;

// For |default$timer.
logic [DEBOUNCE : 0] DEFAULT_timer_n1,
                     DEFAULT_timer_a0;




   //
   // Scope: |default
   //

      // Staging of $timer.
      always_ff @(posedge clk) DEFAULT_timer_a0[DEBOUNCE : 0] <= DEFAULT_timer_n1[DEBOUNCE : 0];


      //
      // Scope: /gpio[N-1:0]
      //
      for (gpio = 0; gpio <= N-1; gpio++) begin : L1gen_DEFAULT_Gpio
         // Staging of $line.
         always_ff @(posedge clk) L1_DEFAULT_Gpio[gpio].L1_line_a0[1 : 0] <= L1_DEFAULT_Gpio[gpio].L1_line_n1[1 : 0];

         // Staging of $read.
         always_ff @(posedge clk) L1_DEFAULT_Gpio[gpio].L1_read_a0 <= L1_DEFAULT_Gpio[gpio].L1_read_n1;

         // Staging of $sync.
         always_ff @(posedge clk) L1_DEFAULT_Gpio[gpio].L1_sync_a0[1 : 0] <= L1_DEFAULT_Gpio[gpio].L1_sync_n1[1 : 0];

      end


// ---------- Generated Code Ends ----------
//_\TLV
   // Connect Verilog inputs:
   //_|default
      //_@0
         assign DEFAULT_gpio_in_a0[N-1:0] = gpio_in;
   //_\source wip.tlv 6   // Instantiated from wip.tlv, 67 as: m5+input_debouncer(/top)
      //_|default
         //_@0
            /*SV_plus*/
               // Synchronize the asynchronous, negatively-asserted reset input, asserting
               // asynchronously but deasserting synchronously to avoid recovery/removal
               // timing issues and metastability.
               always_ff @(posedge clk or negedge rstz) begin
                   if (~ rstz) begin
                       DEFAULT_resetn_meta_a0 <= 1'b0;
                       DEFAULT_resetn_a0 <= 1'b0;
                   end else begin
                       DEFAULT_resetn_meta_a0 <= 1'b1;
                       DEFAULT_resetn_a0 <= DEFAULT_resetn_meta_a0;
                   end
               end
            assign DEFAULT_timer_n1[DEBOUNCE : 0] = ~ DEFAULT_resetn_a0 ? '0 : DEFAULT_tick_a0 ? '0 : DEFAULT_timer_a0 + 1'b1;
            assign DEFAULT_tick_a0 = DEFAULT_timer_a0[DEBOUNCE];
            for (gpio = 0; gpio <= N-1; gpio++) begin : L1_DEFAULT_Gpio logic [1 : 0] L1_line_n1, L1_line_a0; logic [2 : 0] L1_poll_a0; logic L1_raw_val_a0; logic L1_read_n1, L1_read_a0; logic [1 : 0] L1_sync_n1, L1_sync_a0; //_/gpio
               // sync inputs
               assign L1_sync_n1[1 : 0] = {L1_sync_a0[0], DEFAULT_gpio_in_a0[gpio]};
               assign L1_raw_val_a0 = L1_sync_a0[1];
               assign L1_poll_a0[2 : 0] = {L1_line_a0, L1_raw_val_a0};
               assign L1_line_n1[1 : 0] = DEFAULT_tick_a0 ? {L1_line_a0[0], L1_raw_val_a0} : L1_line_a0;
   
               // Record line value on every tick
               // And if stable (three consecutive reads are the same), latch it
               assign L1_read_n1 =
                   DEFAULT_tick_a0 ?
                       (L1_poll_a0 == '0) ? 1'b0 :
                       (L1_poll_a0 == '1) ? 1'b1 :
                       L1_read_a0 :
                   L1_read_a0;
   
               // Connect Verilog outputs:
               assign read[gpio] = L1_read_a0; end
   //_\end_source
//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
