//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 57

//_\SV
   // Copyright (c) 2020 Sonal Pinto
   // SPDX-License-Identifier: Apache-2.0
   //
   // Converted to TL-Verilog by Claude.

   /*
   Staggered 64b counter for Kronos RISC-V

   The counter is made of two 32b counters splitting the critical path
   for lower-end implementations (ex: Lattice iCE40UP)
   The upper word update is delayed by a cycle
   */

   module kronos_counter64 #(
     parameter EN_COUNTERS = 1,
     parameter EN_COUNTERS64B = 1
   )(
     input  logic        clk,
     input  logic        rstz,
     input  logic        incr,
     input  logic [31:0] load_data,
     input  logic        load_low,
     input  logic        load_high,
     output logic [63:0] count,
     output logic        count_vld
   );
// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$count.
logic [63:0] DEFAULT_count_a0;

// For |default$count_high.
logic [31:0] DEFAULT_count_high_n1,
             DEFAULT_count_high_a0;

// For |default$count_low.
logic [31:0] DEFAULT_count_low_n1,
             DEFAULT_count_low_a0;

// For |default$count_vld.
logic DEFAULT_count_vld_a0;

// For |default$incr.
logic DEFAULT_incr_a0;

// For |default$incr_high.
logic DEFAULT_incr_high_n1,
      DEFAULT_incr_high_a0;

// For |default$load_data.
logic [31:0] DEFAULT_load_data_a0;

// For |default$load_high.
logic DEFAULT_load_high_a0;

// For |default$load_low.
logic DEFAULT_load_low_a0;

// For |default$reset.
logic DEFAULT_reset_a0;

// For |default$resetn.
logic DEFAULT_resetn_a0;

// For |default$resetn_meta.
logic DEFAULT_resetn_meta_a0;

// For |default$rstz.
logic DEFAULT_rstz_a0;




   //
   // Scope: |default
   //

      // Staging of $count_high.
      always_ff @(posedge clk) DEFAULT_count_high_a0[31:0] <= DEFAULT_count_high_n1[31:0];

      // Staging of $count_low.
      always_ff @(posedge clk) DEFAULT_count_low_a0[31:0] <= DEFAULT_count_low_n1[31:0];

      // Staging of $incr_high.
      always_ff @(posedge clk) DEFAULT_incr_high_a0 <= DEFAULT_incr_high_n1;



// ---------- Generated Code Ends ----------
//_\TLV
   // Connect Verilog inputs:
   //_|default
      //_@0
         assign DEFAULT_rstz_a0 = rstz;
         assign DEFAULT_incr_a0 = incr;
         assign DEFAULT_load_data_a0[31:0] = load_data;
         assign DEFAULT_load_low_a0 = load_low;
         assign DEFAULT_load_high_a0 = load_high;
   //_\source wip.tlv 6   // Instantiated from wip.tlv, 95 as: m5+kronos_counter64(/top)
      //_|default
         //_@0
            /*SV_plus*/
               // Synchronize the asynchronous, negatively-asserted reset (rstz) into a
               // synchronous, negatively-asserted reset (resetn), using a standard two-flop
               // synchronizer (async assert, sync deassert). This is a deliberate,
               // unverifiable-vs-original functional change; see tracker.md. This
               // block cannot be expressed as TL-Verilog pipesignal assignments since
               // it requires an async-reset-sensitive always_ff (TL-Verilog assumes a
               // single free-running clock).
               always_ff @(posedge clk or negedge DEFAULT_rstz_a0) begin
                 if (~ DEFAULT_rstz_a0) begin
                   DEFAULT_resetn_meta_a0 <= 1'b0;
                   DEFAULT_resetn_a0 <= 1'b0;
                 end
                 else begin
                   DEFAULT_resetn_meta_a0 <= 1'b1;
                   DEFAULT_resetn_a0 <= DEFAULT_resetn_meta_a0;
                 end
               end
   
            assign DEFAULT_reset_a0 = ~ DEFAULT_resetn_a0;
   
            // during a load (any segment), the count is paused
            assign DEFAULT_count_low_n1[31:0] =
              DEFAULT_reset_a0      ? '0 :
              DEFAULT_load_low_a0   ? DEFAULT_load_data_a0 :
              DEFAULT_load_high_a0  ? DEFAULT_count_low_a0 :
              DEFAULT_incr_a0       ? DEFAULT_count_low_a0 + 1'b1 :
                             DEFAULT_count_low_a0;
   
            assign DEFAULT_count_high_n1[31:0] =
              DEFAULT_reset_a0      ? '0 :
              DEFAULT_load_low_a0   ? DEFAULT_count_high_a0 :
              DEFAULT_load_high_a0  ? DEFAULT_load_data_a0 :
              DEFAULT_incr_high_a0  ? DEFAULT_count_high_a0 + 1'b1 :
                             DEFAULT_count_high_a0;
   
            // indicate that the upper word needs to increment
            assign DEFAULT_incr_high_n1 =
              DEFAULT_reset_a0                                  ? 1'b0 :
              (! DEFAULT_load_low_a0 && ! DEFAULT_load_high_a0 && DEFAULT_incr_a0)  ? DEFAULT_count_low_a0 == '1 :
                                                          1'b0;
   
            // relevant if (EN_COUNTERS && EN_COUNTERS64B): the output 64b count is valid
            // when the upper word update has settled
            // relevant if (EN_COUNTERS && ! EN_COUNTERS64B): the upper word will be optimized out
            assign DEFAULT_count_a0[63:0] = (EN_COUNTERS && EN_COUNTERS64B) ? {DEFAULT_count_high_a0, DEFAULT_count_low_a0} :
                           EN_COUNTERS                     ? {32'b0, DEFAULT_count_low_a0} :
                                                              64'b0;
            assign DEFAULT_count_vld_a0 = (EN_COUNTERS && EN_COUNTERS64B) ? ~ DEFAULT_incr_high_a0 : 1'b1;
   //_\end_source
   // Connect Verilog outputs:
   //_|default
      //_@0
         assign count = DEFAULT_count_a0;
         assign count_vld = DEFAULT_count_vld_a0;
//_\SV
   endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
